# Generated by Django 5.0.6 on 2024-06-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='requirement_footage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
