# Generated by Django 5.0.6 on 2024-06-05 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modality', '0001_initial'),
        ('neighborhood', '0001_initial'),
        ('type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rooms', models.IntegerField()),
                ('suites', models.IntegerField()),
                ('garage', models.IntegerField()),
                ('street', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_tel', models.TextField(max_length=25)),
                ('comission', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_of_properties', models.IntegerField(default=1)),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modality.modality')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='neighborhood.neighborhood')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='type.type')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
