# Generated by Django 5.0.6 on 2024-06-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_owner_name_alter_inventory_owner_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='footage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
